# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Chris\Documents\guiwithstatusbar.ui',
# licensing of 'C:\Users\Chris\Documents\guiwithstatusbar.ui' applies.
#
# Created: Tue Sep  4 02:53:04 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528474042
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCharts import QtCharts
from PySide2.QtCore import Slot, QSortFilterProxyModel, Qt, QDateTime
from PySide2.QtGui import QPainter, QStandardItemModel
import Database,ImageProcessing,keyboard
import APIconnection



class CustomWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(CustomWidget, self).__init__(parent)

    def paintEvent(self, event):

        opt = QtWidgets.QStyleOption()
        opt.init(self)
        painter = QtGui.QPainter(self)
        self.style().drawPrimitive(QtWidgets.QStyle.PE_Widget, opt, painter, self)


class Ui_MainWindow(object):
    def __init__(self):
            self.DBConnection = Database.RainbowDB()
            self.ImageProcessing_OBJ = None

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 515)
        MainWindow.setMinimumSize(QtCore.QSize(888, 515))
        self.MainWindowCentralWidget = CustomWidget(MainWindow)
        self.MainWindowCentralWidget.setObjectName("MainWindowCentralWidget")
        contents = b"<svg width='44' height='12' viewBox='0 0 44 12' xmlns='http://www.w3.org/2000/svg'><path d='M20 12v-2L0 0v10l4 2h16zm18 0l4-2V0L22 10v2h16zM20 0v8L4 0h16zm18 0L22 8V0h16z' fill='#2c2c2c' fill-opacity='0.4' fill-rule='evenodd'/></svg>"
        file = QtCore.QTemporaryFile(self.MainWindowCentralWidget)
        if file.open():
            file.write(contents)
            file.flush()
            self.MainWindowCentralWidget.setStyleSheet("""CustomWidget#MainWindowCentralWidget{background-color: #000000;
                                  background-image: url(%s);}""" % file.fileName())
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainWindowCentralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.MainWindowCentralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.HomePage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.HomePageLogoLabel = QtWidgets.QLabel(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomePageLogoLabel.sizePolicy().hasHeightForWidth())
        self.HomePageLogoLabel.setSizePolicy(sizePolicy)
        self.HomePageLogoLabel.setMinimumSize(QtCore.QSize(200, 60))
        self.HomePageLogoLabel.setMaximumSize(QtCore.QSize(200, 60))
        self.HomePageLogoLabel.setText("")
        self.HomePageLogoLabel.setPixmap(QtGui.QPixmap(r"C:\Users\Chris\Desktop\ApplicationLogo.png"))
        self.HomePageLogoLabel.setScaledContents(True)
        self.HomePageLogoLabel.setObjectName("HomePageLogoLabel")
        self.verticalLayout.addWidget(self.HomePageLogoLabel)
        self.HomePageHomeButton = QtWidgets.QPushButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.HomePageHomeButton.sizePolicy().hasHeightForWidth())
        self.HomePageHomeButton.setSizePolicy(sizePolicy)
        self.HomePageHomeButton.setMinimumSize(QtCore.QSize(200, 23))
        self.HomePageHomeButton.setObjectName("HomePageHomeButton")
        self.verticalLayout.addWidget(self.HomePageHomeButton)
        self.HomePageStatisticsButton = QtWidgets.QPushButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.HomePageStatisticsButton.sizePolicy().hasHeightForWidth())
        self.HomePageStatisticsButton.setSizePolicy(sizePolicy)
        self.HomePageStatisticsButton.setMinimumSize(QtCore.QSize(200, 23))
        self.HomePageStatisticsButton.setObjectName("HomePageStatisticsButton")
        self.HomePageStatisticsButton.clicked.connect(self.Go_stats)
        self.verticalLayout.addWidget(self.HomePageStatisticsButton)
        self.HomePageSettingsButton = QtWidgets.QPushButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.HomePageSettingsButton.sizePolicy().hasHeightForWidth())
        self.HomePageSettingsButton.setSizePolicy(sizePolicy)
        self.HomePageSettingsButton.setMinimumSize(QtCore.QSize(200, 23))
        self.HomePageSettingsButton.setObjectName("HomePageSettingsButton")
        self.HomePageSettingsButton.clicked.connect(self.Go_settings)
        self.verticalLayout.addWidget(self.HomePageSettingsButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.HomePageKillCamListWidget = QtWidgets.QListWidget(self.HomePage)
        self.HomePageKillCamListWidget.setAutoScroll(False)
        self.HomePageKillCamListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.HomePageKillCamListWidget.setProperty("showDropIndicator", False)
        self.HomePageKillCamListWidget.setAlternatingRowColors(False)
        self.HomePageKillCamListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.HomePageKillCamListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.HomePageKillCamListWidget.setViewMode(QtWidgets.QListWidget.IconMode)
        self.HomePageKillCamListWidget.setObjectName("HomePageKillCamListWidget")
        self.horizontalLayout_2.addWidget(self.HomePageKillCamListWidget)
        self.stackedWidget.addWidget(self.HomePage)
        self.StatsPage = QtWidgets.QWidget()
        self.StatsPage.setObjectName("StatsPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.StatsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.StatisticsPageHomeButton = QtWidgets.QPushButton(self.StatsPage)
        self.StatisticsPageHomeButton.setObjectName("StatisticsPageHomeButton")
        self.StatisticsPageHomeButton.clicked.connect(self.Go_home)
        self.horizontalLayout_3.addWidget(self.StatisticsPageHomeButton)
        self.StatisticsPageStatistics = QtWidgets.QPushButton(self.StatsPage)
        self.StatisticsPageStatistics.setObjectName("StatisticsPageStatistics")
        self.horizontalLayout_3.addWidget(self.StatisticsPageStatistics)
        self.StatisticsPageSettingsButton = QtWidgets.QPushButton(self.StatsPage)
        self.StatisticsPageSettingsButton.setObjectName("StatisticsPageSettingsButton")
        self.StatisticsPageSettingsButton.clicked.connect(self.Go_settings)
        self.horizontalLayout_3.addWidget(self.StatisticsPageSettingsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.StatisticsPageTableView = QtWidgets.QTableView(self.StatsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatisticsPageTableView.sizePolicy().hasHeightForWidth())
        self.StatisticsPageTableView.setSizePolicy(sizePolicy)
        self.StatisticsPageTableView.setMinimumSize(QtCore.QSize(350, 0))
        self.StatisticsPageTableView.setAutoScroll(False)
        self.StatisticsPageTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.StatisticsPageTableView.setTabKeyNavigation(False)
        self.StatisticsPageTableView.setProperty("showDropIndicator", False)
        self.StatisticsPageTableView.setDragDropOverwriteMode(False)
        self.StatisticsPageTableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.StatisticsPageTableView.setSortingEnabled(True)
        self.StatisticsPageTableView.setCornerButtonEnabled(False)
        self.StatisticsPageTableView.setObjectName("StatisticsPageTableView")
        self.horizontalLayout_4.addWidget(self.StatisticsPageTableView)
        self.StatisticsPageTabWidget = QtWidgets.QTabWidget(self.StatsPage)
        self.StatisticsPageTabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.StatisticsPageTabWidget.setObjectName("StatisticsPageTabWidget")
        self.HistogramTab = QtWidgets.QWidget()
        self.HistogramTab.setObjectName("HistogramTab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.HistogramTab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.StatisticsPageTabWidget.addTab(self.HistogramTab, "")
        self.PieChartTab = QtWidgets.QWidget()
        self.PieChartTab.setObjectName("PieChartTab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.PieChartTab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.StatisticsPageTabWidget.addTab(self.PieChartTab, "")
        self.horizontalLayout_4.addWidget(self.StatisticsPageTabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.StatsPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SettingsPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.SettingsPageHomeButton = QtWidgets.QPushButton(self.SettingsPage)
        self.SettingsPageHomeButton.setObjectName("SettingsPageHomeButton")
        self.SettingsPageHomeButton.clicked.connect(self.Go_home)
        self.horizontalLayout_6.addWidget(self.SettingsPageHomeButton)
        self.SettingsPageStatisticsButton = QtWidgets.QPushButton(self.SettingsPage)
        self.SettingsPageStatisticsButton.setObjectName("SettingsPageStatisticsButton")
        self.horizontalLayout_6.addWidget(self.SettingsPageStatisticsButton)
        self.SettingsPageStatisticsButton.clicked.connect(self.Go_stats)
        self.SettingsPageSettingsButton = QtWidgets.QPushButton(self.SettingsPage)
        self.SettingsPageSettingsButton.setObjectName("SettingsPageSettingsButton")
        self.horizontalLayout_6.addWidget(self.SettingsPageSettingsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SettingsPageEnableAPILabel = QtWidgets.QLabel(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageEnableAPILabel.sizePolicy().hasHeightForWidth())
        self.SettingsPageEnableAPILabel.setSizePolicy(sizePolicy)
        self.SettingsPageEnableAPILabel.setMinimumSize(QtCore.QSize(200, 20))
        self.SettingsPageEnableAPILabel.setMaximumSize(QtCore.QSize(200, 20))
        self.SettingsPageEnableAPILabel.setText("")
        self.SettingsPageEnableAPILabel.setPixmap(QtGui.QPixmap(r"C:\Users\Chris\Desktop\EnableAPITextCropped2.0.png"))
        self.SettingsPageEnableAPILabel.setScaledContents(True)
        self.SettingsPageEnableAPILabel.setObjectName("SettingsPageEnableAPILabel")
        self.verticalLayout_4.addWidget(self.SettingsPageEnableAPILabel)
        self.SettingsAPIEnabledDisabledLabel = QtWidgets.QLabel(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsAPIEnabledDisabledLabel.sizePolicy().hasHeightForWidth())
        self.SettingsAPIEnabledDisabledLabel.setSizePolicy(sizePolicy)
        self.SettingsAPIEnabledDisabledLabel.setMinimumSize(QtCore.QSize(250, 13))
        self.SettingsAPIEnabledDisabledLabel.setMaximumSize(QtCore.QSize(250, 13))
        self.SettingsAPIEnabledDisabledLabel.setObjectName("SettingsAPIEnabledDisabledLabel")
        self.verticalLayout_4.addWidget(self.SettingsAPIEnabledDisabledLabel)
        self.SettingsPageEmailLineEdit = QtWidgets.QLineEdit(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageEmailLineEdit.sizePolicy().hasHeightForWidth())
        self.SettingsPageEmailLineEdit.setSizePolicy(sizePolicy)
        self.SettingsPageEmailLineEdit.setMinimumSize(QtCore.QSize(250, 20))
        self.SettingsPageEmailLineEdit.setMaximumSize(QtCore.QSize(250, 20))
        self.SettingsPageEmailLineEdit.setObjectName("SettingsPageEmailLineEdit")
        self.verticalLayout_4.addWidget(self.SettingsPageEmailLineEdit)
        self.SettingsPagePasswordLineEdit = QtWidgets.QLineEdit(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPagePasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.SettingsPagePasswordLineEdit.setSizePolicy(sizePolicy)
        self.SettingsPagePasswordLineEdit.setMinimumSize(QtCore.QSize(250, 23))
        self.SettingsPagePasswordLineEdit.setMaximumSize(QtCore.QSize(250, 23))
        self.SettingsPagePasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.SettingsPagePasswordLineEdit.setObjectName("SettingsPagePasswordLineEdit")
        self.verticalLayout_4.addWidget(self.SettingsPagePasswordLineEdit)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.SettingsPageSaveButton = QtWidgets.QPushButton(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageSaveButton.sizePolicy().hasHeightForWidth())
        self.SettingsPageSaveButton.setSizePolicy(sizePolicy)
        self.SettingsPageSaveButton.setMinimumSize(QtCore.QSize(100, 23))
        self.SettingsPageSaveButton.setMaximumSize(QtCore.QSize(92, 23))
        self.SettingsPageSaveButton.setObjectName("SettingsPageSaveButton")
        self.SettingsPageSaveButton.clicked.connect(self.Validate_Ubisoft_Account)
        self.horizontalLayout_7.addWidget(self.SettingsPageSaveButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.SettingsPageClearLoginButton = QtWidgets.QPushButton(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageClearLoginButton.sizePolicy().hasHeightForWidth())
        self.SettingsPageClearLoginButton.setSizePolicy(sizePolicy)
        self.SettingsPageClearLoginButton.setMinimumSize(QtCore.QSize(250, 23))
        self.SettingsPageClearLoginButton.setMaximumSize(QtCore.QSize(250, 23))
        self.SettingsPageClearLoginButton.setObjectName("SettingsPageClearLoginButton")
        self.verticalLayout_4.addWidget(self.SettingsPageClearLoginButton)
        self.SettingsPageClearDatabaseLabel = QtWidgets.QLabel(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageClearDatabaseLabel.sizePolicy().hasHeightForWidth())
        self.SettingsPageClearDatabaseLabel.setSizePolicy(sizePolicy)
        self.SettingsPageClearDatabaseLabel.setMinimumSize(QtCore.QSize(250, 20))
        self.SettingsPageClearDatabaseLabel.setMaximumSize(QtCore.QSize(250, 20))
        self.SettingsPageClearDatabaseLabel.setText("")
        self.SettingsPageClearDatabaseLabel.setPixmap(QtGui.QPixmap(r"C:\Users\Chris\Desktop\cleardatabaseimage.png"))
        self.SettingsPageClearDatabaseLabel.setScaledContents(True)
        self.SettingsPageClearDatabaseLabel.setObjectName("SettingsPageClearDatabaseLabel")
        self.verticalLayout_4.addWidget(self.SettingsPageClearDatabaseLabel)
        self.SettingsPageClearDatabaseButton = QtWidgets.QPushButton(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageClearDatabaseButton.sizePolicy().hasHeightForWidth())
        self.SettingsPageClearDatabaseButton.setSizePolicy(sizePolicy)
        self.SettingsPageClearDatabaseButton.setMinimumSize(QtCore.QSize(250, 23))
        self.SettingsPageClearDatabaseButton.setMaximumSize(QtCore.QSize(250, 23))
        self.SettingsPageClearDatabaseButton.setObjectName("SettingsPageClearDatabaseButton")
        self.verticalLayout_4.addWidget(self.SettingsPageClearDatabaseButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SettingsPageHotkeysLabel = QtWidgets.QLabel(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPageHotkeysLabel.sizePolicy().hasHeightForWidth())
        self.SettingsPageHotkeysLabel.setSizePolicy(sizePolicy)
        self.SettingsPageHotkeysLabel.setMinimumSize(QtCore.QSize(200, 20))
        self.SettingsPageHotkeysLabel.setMaximumSize(QtCore.QSize(250, 20))
        self.SettingsPageHotkeysLabel.setText("")
        self.SettingsPageHotkeysLabel.setPixmap(QtGui.QPixmap(r"C:\Users\Chris\Desktop\Selecthotkeys.png"))
        self.SettingsPageHotkeysLabel.setScaledContents(True)
        self.SettingsPageHotkeysLabel.setObjectName("SettingsPageHotkeysLabel")
        self.verticalLayout_5.addWidget(self.SettingsPageHotkeysLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SettingsPageHotkeySpinboxTwo = QtWidgets.QSpinBox(self.SettingsPage)
        self.SettingsPageHotkeySpinboxTwo.setObjectName("SettingsPageHotkeySpinboxTwo")
        self.horizontalLayout_8.addWidget(self.SettingsPageHotkeySpinboxTwo)
        self.SettingsPageHotkeySpinboxOne = QtWidgets.QSpinBox(self.SettingsPage)
        self.SettingsPageHotkeySpinboxOne.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SettingsPageHotkeySpinboxOne.setObjectName("SettingsPageHotkeySpinboxOne")
        self.horizontalLayout_8.addWidget(self.SettingsPageHotkeySpinboxOne)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.SettingsPage)
        self.GrieferPage = QtWidgets.QWidget()
        self.GrieferPage.setObjectName("GrieferPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.GrieferPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.GrieferPageHomeButton = QtWidgets.QPushButton(self.GrieferPage)
        self.GrieferPageHomeButton.setObjectName("GrieferPageHomeButton")
        self.GrieferPageHomeButton.clicked.connect(self.Go_home)
        self.horizontalLayout_12.addWidget(self.GrieferPageHomeButton)
        self.GrieferPageStatisticsButton = QtWidgets.QPushButton(self.GrieferPage)
        self.GrieferPageStatisticsButton.setObjectName("GrieferPageStatisticsButton")
        self.GrieferPageStatisticsButton.clicked.connect(self.Go_stats)
        self.horizontalLayout_12.addWidget(self.GrieferPageStatisticsButton)
        self.GrieferPageSettingsButton = QtWidgets.QPushButton(self.GrieferPage)
        self.GrieferPageSettingsButton.setObjectName("GrieferPageSettingsButton")
        self.GrieferPageSettingsButton.clicked.connect(self.Go_settings)
        self.horizontalLayout_12.addWidget(self.GrieferPageSettingsButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.GrieferPageGrieferNamesLabel = QtWidgets.QLabel(self.GrieferPage)
        self.GrieferPageGrieferNamesLabel.setMinimumSize(QtCore.QSize(250, 20))
        self.GrieferPageGrieferNamesLabel.setMaximumSize(QtCore.QSize(250, 20))
        self.GrieferPageGrieferNamesLabel.setText("")
        self.GrieferPageGrieferNamesLabel.setPixmap(QtGui.QPixmap(r"C:\Users\Chris\Desktop\griefernames.png"))
        self.GrieferPageGrieferNamesLabel.setScaledContents(True)
        self.GrieferPageGrieferNamesLabel.setObjectName("GrieferPageGrieferNamesLabel")
        self.verticalLayout_7.addWidget(self.GrieferPageGrieferNamesLabel)
        self.GrieferPageGrieferNamesListWidget = QtWidgets.QListWidget(self.GrieferPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GrieferPageGrieferNamesListWidget.sizePolicy().hasHeightForWidth())
        self.GrieferPageGrieferNamesListWidget.setSizePolicy(sizePolicy)
        self.GrieferPageGrieferNamesListWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.GrieferPageGrieferNamesListWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.GrieferPageGrieferNamesListWidget.setAutoScroll(False)
        self.GrieferPageGrieferNamesListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.GrieferPageGrieferNamesListWidget.setProperty("showDropIndicator", False)
        self.GrieferPageGrieferNamesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.GrieferPageGrieferNamesListWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.GrieferPageGrieferNamesListWidget.setObjectName("GrieferPageGrieferNamesListWidget")
        self.verticalLayout_7.addWidget(self.GrieferPageGrieferNamesListWidget)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.GrieferPageKillCamListWidget = QtWidgets.QListWidget(self.GrieferPage)
        self.GrieferPageKillCamListWidget.setAutoScroll(False)
        self.GrieferPageKillCamListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.GrieferPageKillCamListWidget.setProperty("showDropIndicator", False)
        self.GrieferPageKillCamListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.GrieferPageKillCamListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.GrieferPageKillCamListWidget.setViewMode(QtWidgets.QListWidget.IconMode)
        self.GrieferPageKillCamListWidget.setObjectName("GrieferPageKillCamListWidget")
        self.horizontalLayout_11.addWidget(self.GrieferPageKillCamListWidget)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.GrieferPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.MainWindowCentralWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #################### Initial setup of table view model on stats page ########################################
        self.stats_page_table_view_model = QStandardItemModel(0,3)
        self.proxymodel = QSortFilterProxyModel(self.StatsPage)
        self.proxymodel.setSourceModel(self.stats_page_table_view_model)
        self.StatisticsPageTableView.setModel(self.proxymodel)
        self.StatisticsPageTableView.setSortingEnabled(True)
        self.stats_page_table_view_model.setHeaderData(0,Qt.Horizontal,"Name")
        self.stats_page_table_view_model.setHeaderData(1,Qt.Horizontal,"Incidents")
        self.stats_page_table_view_model.setHeaderData(2,Qt.Horizontal,"Date")
        self.StatisticsPageTableView.verticalHeader().setVisible(False)
        #############################################################################################################
        ######################### Initial setup of main window list widget that displays killcams#####################
        self.setup_listwidget()
        #############################################################################################################

        ######################### Initial setup of stats window table view that displays griefer data################
        self.setup_tableview()
        #############################################################################################################

        ######################## Initial setup of stats window barchart that displays griefer kill data##############


        self.chart = QtCharts.QChart()
        self.grieferset = QtCharts.QBarSet("Incidents")
        self.Setup_bar_chart()
        self.chartView = QtCharts.QChartView(self.chart)
        self.chartView.setRenderHint(QPainter.Antialiasing)
        self.horizontalLayout_9.addWidget(self.chartView)
        #############################################################################################################


        ######################################################################Status bar CSS#########################



        self.statusbar.setStyleSheet("QStatusBar::item{border: 0px;} QStatusBar{min-height:20; background-color:rgb(186,0,0);}")
        self.statusbar.addWidget(QtWidgets.QLabel("Enter Ubisoft Credentials To Enable API"))

        #############################################################################################################


        self.HomePageKillCamListWidget.setIconSize(QtCore.QSize(202,202))

        self.GrieferPageKillCamListWidget.setIconSize(QtCore.QSize(202,202))

        ##############################################################################################################
        self.retranslateUi(MainWindow)
        self.StatisticsPageTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.HomePageHomeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.HomePageStatisticsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.HomePageSettingsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.StatisticsPageHomeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.StatisticsPageStatistics.setText(QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.StatisticsPageSettingsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.StatisticsPageTabWidget.setTabText(self.StatisticsPageTabWidget.indexOf(self.HistogramTab), QtWidgets.QApplication.translate("MainWindow", "Histogram", None, -1))
        self.StatisticsPageTabWidget.setTabText(self.StatisticsPageTabWidget.indexOf(self.PieChartTab), QtWidgets.QApplication.translate("MainWindow", "Pie Chart", None, -1))
        self.SettingsPageHomeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.SettingsPageStatisticsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.SettingsPageSettingsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.SettingsAPIEnabledDisabledLabel.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.SettingsPageEmailLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ubisoft Email", None, -1))
        self.SettingsPagePasswordLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ubisoft Password", None, -1))
        self.SettingsPageSaveButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.SettingsPageClearLoginButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Login Details", None, -1))
        self.SettingsPageClearDatabaseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Database", None, -1))
        self.GrieferPageHomeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.GrieferPageStatisticsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.GrieferPageSettingsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))


    def StartMonitoring(self):
        self.ImageProcessing_OBJ = ImageProcessing.siege_image_process()
        self.ImageProcessing_OBJ.im_new_image.connect(self.new_screenshot_listwidget)
        self.ImageProcessing_OBJ.im_player_path_dict.connect(self.Switch_and_Generate_pp)
        keyboard.add_hotkey(hotkey = "j+k", callback= self.ImageProcessing_OBJ.check_kcam_sboard)
        keyboard.add_hotkey(hotkey = "tab+j+k", callback= self.ImageProcessing_OBJ.check_kcam_sboard)


    @Slot(dict)
    def Switch_and_Generate_pp(self,playerdict):
        self.stackedWidget.setCurrentIndex(3)
        self.GrieferPageKillCamListWidget.clear()
        self.GrieferPageGrieferNamesListWidget.clear()
        print(playerdict)
        self.playername_string = ""
        for player in playerdict:
            self.GrieferPageGrieferNamesListWidget.addItem(QtWidgets.QListWidgetItem(player))
            self.playername_string +=  player +","
            for path in playerdict[player]:
                self.GrieferPageKillCamListWidget.addItem(QtWidgets.QListWidgetItem(QtGui.QIcon
                    (path), player))



    def new_screenshot_listwidget(self,path):
        self.HomePageKillCamListWidget.addItem(QtWidgets.QListWidgetItem(QtGui.QIcon
                    (path),None))
    def setup_tableview(self):

        for player,list in self.DBConnection.player_kill_count_date().items():
            self.stats_page_table_view_model.insertRow(0)
            self.stats_page_table_view_model.setData(self.stats_page_table_view_model.index(0,0),player)
            self.stats_page_table_view_model.setData(self.stats_page_table_view_model.index(0,1),list[0])
            self.stats_page_table_view_model.setData(self.stats_page_table_view_model.index(0,2),list[1])

    def setup_listwidget(self):
        for path in self.DBConnection.get_all_player_paths():
            self.HomePageKillCamListWidget.addItem(QtWidgets.QListWidgetItem(QtGui.QIcon
                    (path[0]),None))
    def Setup_bar_chart(self):
        self.kcdict = self.DBConnection.player_kill_counts()
        self.grieferset.append([self.kcdict[player] for player in (sorted(self.kcdict, key = lambda x: -self.kcdict[x])[:5])])
        print(self.kcdict)
        self.barSeries = QtCharts.QBarSeries()
        self.barSeries.append(self.grieferset)
        self.chart.addSeries(self.barSeries)
        self.chart.setTitle("Top Griefers By Incidents")
        self.categories = sorted(self.kcdict, key = lambda x: -self.kcdict[x])[:5]
        print("these are the categories", self.categories)
        self.axisX = QtCharts.QBarCategoryAxis()
        self.axisX.append(self.categories)
        self.chart.setAxisX(self.axisX, self.barSeries)
        self.axisY = QtCharts.QValueAxis()

        self.chart.setAxisY(self.axisY, self.barSeries)
    def Validate_Ubisoft_Account(self):
        if APIconnection.API_connection.validate_log_in_details(self.SettingsPageEmailLineEdit.text(), self.SettingsPagePasswordLineEdit.text()):
            self.SettingsAPIEnabledDisabledLabel.setText("API active using account: " + self.SettingsPageEmailLineEdit.text())
            self.SettingsAPIEnabledDisabledLabel.setStyleSheet("color: green")
            self.StartMonitoring()
            self.statusbar.hide()
        else:
            self.SettingsAPIEnabledDisabledLabel.setText("API Not active")
            self.SettingsAPIEnabledDisabledLabel.setStyleSheet("color: red")

    def Go_home(self):
        self.stackedWidget.setCurrentIndex(0)
    def Go_stats(self):
        self.stackedWidget.setCurrentIndex(1)
    def Go_settings(self):
        self.stackedWidget.setCurrentIndex(2)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
